CREATE TABLE games (
    game_date_est    DATE,
    game_id          INT NOT NULL,
    game_status_text VARCHAR(255),
    home_team_id     INT,
    visitor_team_id  INT,
    season           INT,
    team_id_home     INT,
    pts_home         FLOAT,
    fg_pct_home      FLOAT,
    ft_pct_home      FLOAT,
    fg3_pct_home     FLOAT,
    ast_home         FLOAT,
    reb_home         FLOAT,
    team_id_away     INT,
    pts_away         FLOAT,
    fg_pct_away      FLOAT,
    ft_pct_away      FLOAT,
    fg3_pct_away     FLOAT,
    ast_away         FLOAT,
    reb_away         FLOAT,
    home_team_wins   TINYINT(1),
    KEY idx_games_game_id (game_id),
    KEY idx_games_season (season)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;